from etl import ler_csv, filtrar_produtos_nao_entregues, somar_valores_produtos_nao_entregues

path_arquivo="desafio/vendas.csv"


lista_de_produtos=ler_csv(path_arquivo)
produtos_entregues=filtrar_produtos_nao_entregues(lista_de_produtos)
valor_dos_produtos_entregues=somar_valores_produtos_nao_entregues(produtos_entregues)

